SetRandomSeed(2352, 9533) -- hax?

---@type string[][]
DIALOGUE_DAMAGEDEALT = {
    {"$animal_shotgunner", "Gotcha.", "Blood, blood!", "I hope that hurt."},
    {"$animal_zombie", "Tasty!", "Rah!", "Spill your blood!"},
    {"$animal_chest_mimic", "Fool! FOOOOL!", "Boo! I bet you didn't expect that!", "Hahaha! Got ya!"},
    {"$animal_dark_alchemist", "EAHAHAHA!", "HAHA!!", "MUAHAHAHA!"},
    {"$animal_shaman_wind", "EAHAHAHA!", "HAHA!!", "MUAHAHAHA!"},
    {"$animal_longleg", "Fall before us!", "Fear us!", "We are legion!"},
    {"$animal_miner", "Nice catch! Haha...", "Kaboom!", "I expected more from you."},
    {"$animal_firemage", "You're not looking so hot.", "Can't handle the heat? I get it.", "You look a bit burnt. That won't do at all..."},
    {"$animal_firemage_weak", "You're a fool!", "You'd best run while you still can.", "I like my food cooked well-done."},
    {"$animal_slimeshooter", "Splat!", "Are you feeling the toxicity yet?", "Let it seep into your skin..."},
    {"$animal_acidshooter", "Meet your end.", "Goodbye.", "You won't be missed."},
    {"$animal_giantshooter", "Fuel for the fire...", "You taste terrible.", "You will become food for my children!"},
    {"$animal_frog", "Konna used Tackle!", "I got you!", "Watch me fly!"},
    {"$animal_frog_big", "Blah!", "Blorp!", "Mlem."},
    {"$animal_miner_fire", "Eat this!", "Serves you right!", "Feel the burn!"},
    {"$animal_graham_miner_gasser", "Breathe it in...", "I wear this hazmat suit for a reason.", "It's nothing personal. Let's try to make it quick."},
    {"$animal_boss_pit", "Experience the TRUE power of magic!", "How does it feel? Does it hurt? Good.", "Prepare to meet your end!", "Be grateful that one didn't polymorph you.", "You'll never amount to anything. You'll just become corrupt...", "I hate plasma. It burns the eye..."},
    {"$animal_shaman", "A curse upon you!", "None of you are free of sin...", "You will be missed."},
    {"$animal_playerghost", "Blame only yourself for this!", "I feel your pain. Haha... what irony.", "Don't fret. You're only one in " .. 1 + StatsGlobalGetValue( "death_count" ) .. "."},
    {"$animal_firebug", "Stand down, intruder!", "Together, we're strong!", "This is our domain! Get out!"},
    {"$animal_bigfirebug", "I'll burn you to a crisp!", "For the Hive, I'll take you down!", "This is my domain! Leave while you still can!"},
    {"$animal_fireskull", "Your end is near!", "I've got you now!", "Raaah!"},
    {"$animal_bat", "Tear them to pieces!", "Bomp.", "Splat."},
    {"$animal_bigbat", "Let's knock them down!", "Stun them, stop them!", "Now! Swarm!"},
    {"$animal_sniper", "If anyone's getting this done, it's going to be me.", "If you forfeit now, I might spare your life! Heh...", "Ouch, you might need surgery after that one."},
    {"$animal_scavenger_grenade", "You're just making my job easier!", "Do you need me to go easy on you?", "Come back when you've learned to dodge!"},
    {"$animal_thundermage", "Farewell, this is your end!", "Feel the electric shock run through your body...", "Oh, this is almost too easy...!"},
    {"$animal_goblin_bomb", "Shrapnel! Pain!", "Haha, yes!", "I did it!"},
    {"$animal_scavenger_heal", "Are you feeling better?", "I hope that helps.", "Deep breaths. You're gonna be okay."},
    {"$animal_boss_alchemist", "Oh, child... If only you knew.", "You're not even worth saving.", "Count this as a mercy kill. You wouldn't want to be like them.", "Life, death, or somewhere in between...? For you, I've chosen death.", "A shame, too... You could have been so great.", "Nothing? Not even a cry of pain? How daft."},
    {"$animal_parallel_tentacles", "You monster.", "Justice is served.", "You deserve no apologies."},
    {"$animal_parallel_alchemist", "Forfeit yourself. Don't end up like me...", "Don't go any further. Damnation awaits you.", "Reality grows more unstable because of you."},
    {"$animal_wizard_poly", "If you survive this, I'll be impressed...", "Are you feeling a bit sheepish...?", "You look rather pale."},
    {"$animal_wizard_dark", "Do you see what I see?", "Rest your weary eyes.", "Open your third eye."},
    {"$animal_wizard_tele", "And off you go!", "Uhuhu! Chaos for you!", "Here's a magic trick: watch this fool disappear!"},
    {"$animal_wizard_returner", "Be not afraid. It's just your reflection.", "Right back at ya!", "That's a taste of your own medicine."},
    {"$animal_wizard_swapper", "Oh! What?!", "No, I just wanted to have fun...!", "Oops...! haha."},
    {"$animal_wizard_neutral", "Signal lost.", "That's all, folks!", "Your move."},
    {"$animal_wizard_twitchy", "Ha-ah-aha...", "G-g-gotcha!", "F-f-feeling just like me?"},
    {"$animal_wizard_hearty", "Half and half and half again.", "I'll round you down to zero.", "You better not collect a heart after this."},
    {"$animal_wizard_weaken", "It's now or never.", "You are now no longer invulnerable. Enjoy.", "Weakening curse? What curse could surpass me?"},
    {"$animal_wizard_homing", "This time it's gotta work, for sure!", "Come, my fellow Masters! Attack now!", "It's not Boomerang Spells, but it'll do."},
    {"$animal_barfer", "I'm confused. W-what happened...?", "I did it? ...I did it!", "Oh... h-hooray!"},
    {"$animal_necromancer_shop", "Your run ends here!", "Beware justice's power! Fear it well!", "I'll snap you in half!"},
    {"$animal_necromancer_super", "I'll send you straight to our Gods, and you'll answer for your sins there.", "By divine wrath, you'll die today!", "I see right through you. You knew this was coming."},
    {"$animal_roboguard", "Come quietly or there will be trouble.", "Your move, creep!", "Dead or alive, you're coming with me!"},
    {"$animal_scavenger_invis", "Hey, this is kind of fun!", "I've never done this before...", "Oh, I see how this works!"},
    {"$animal_scavenger_shield", "I didn't mean to, I swear!", "Oops! I'm sorry!", "No, I didn't mean it!"},
    {"$animal_alchemist", "Oh, I can just deal damage like this? Sweet!", "This was easier than I thought it'd be.", "Catch!"},
    {"$animal_tentacler", "You should've planned an escape route so much sooner...", "You won't slip out of my grasp this time!", "Get a good look at me. I'll make it your last."},
    {"$animal_tentacler_small", "Underestimated me, didja?", "Hehe... Did you forget that I could do that?", "Crunch!"},
    {"$animal_ant", "Ta-da!", "How could you let this happen?", "You lose, sucker!"},
    {"$animal_maggot", "It's like firecrackers! Pop, pop, pop...", "What, did you run out of levitation...?", "Wow! ...What?"},
    {"$animal_fungus_giga", "I hope you don't have allergies.", "You look a bit scraped up...", "Stay back!"},
    {"$animal_fly", "Sting them! Now!", "We produce honey, and you are NOT involved!", "Maybe you should just leave us alone."},
    {"$animal_drone", "Target found. Engaging...", "Attempting to break target's focus...", "Detecting weaknesses... Bullets seem ineffective."},
    {"$animal_bigzombie", "Join the undead... you'll be dying to do so.", "One day you'll end up like me.", "In the end, we'll all be... Dead, but perhaps not buried."},
    {"$animal_bigzombiehead", "Is it still rude to headbutt someone if you only have a head?", "This is what you get for ripping my head off!", "Death is inevitable. I'm just speeding yours up."},
    {"$animal_rat", "Say goodbye to your ankles!", "I hope you've been vaccinated.", "Rip and tear..."},
    {"$animal_iceskull", "Hah, take that to remember me by.", "Beautiful. Hold that pose, right there...", "Making ice sculptures is an intricate art."},
    {"$animal_thunderskull", "Surprised? You should know that shocking people is my specialty!", "Wow, I've never seen someone fall for that before.", "No hard feelings, yeah, dude?"},
    {"$animal_giant", "Step back. Take some time to refresh.", "You're not the first to get lost in the cold.", "What a shame."},
    {"$animal_scavenger_mine", "Yo! Stay out of my range, weirdo.", "Let me hit you a few more times before you touch the ground.", "You're even more helpless than the animals I used to hunt."},
    {"$animal_scavenger_glue", "Oh, this is a sticky situation...", "My job is all for show, y'know? For the paycheck.", "You're looking kind of suspicious there, friend."},
    {"$animal_scavenger_leader", "Get out of my sight.", "Must I do everything myself?", "You've gotta be kidding me."},
    {"$animal_scavenger_smg", "Eat lead, pest!", "Don't even think about levitating away.", "Don't you know? Brawn beats brains."},
    {"$animal_scavenger_clusterbomb", "Dying in the battlefield is honorable. Let me show you.", "This is what happens when consequences catch up to you.", "One of us must die here. I won't let it be me."},
    {"$animal_scavenger_poison", "What's the matter with you?", "I don't care who else dies. You have to go.", "Let me get a good look at you while you die."},
    {"$animal_tank", "I am programmed to know what to do. Not why.", "Stay down. Do not fly away this time.", "Look at you. You are full of holes."},
    {"$animal_tank_rocket", "Fully autonomous and still somehow smarter than you.", "You truly are inferior.", "I had you figured out long ago."},
    {"$animal_tank_super", "Why can you not take what you give?", "Creature of magic, end this now.", "You confound my circuitry."},
    {"$animal_turret", "Target suppressed.", "Hold still.", "You should have expected this."},
    {"$animal_miniblob", "Agitate!", "Fight, fight!", "Squash!"},
    {"$animal_blob", "Take over!", "Invade!", "Annihilate!"},
    {"$animal_necromancer", "Ew. Don't make me do that again.", "That was just to make a point. Now leave.", "Next time, stay far away from me and my magic."},
    {"$animal_monk", "Dissenters will be punished.", "Ignorant little one... Let me re-educate you.", "Sit still. Soon you will be enlightened."},
    {"$animal_worm_tiny", "Boop! Gotcha!", "Just passing through, sorry.", "Oops. I just can't help myself."},
    {"$animal_worm", "I will literally bite anything that can die.", "Hey, my tunnels are only for me! Keep out.", "Guess how many stomachs I have. It's more than you'd think."},
    {"$animal_worm_big", "Don't worry, I'll make sure you get a spot in my biography.", "Even brickwork tastes better than that dirty cloak.", "That's for drinking my blood, you creep!"},
    {"$animal_phantom_a", "Out! All of you, get out!", "Oh, don't think I'd ever forget about you.", "Soon... soon you will all see!"},
    {"$animal_phantom_b", "Am I only in your head? Well, what isn't?", "If this is a nightmare, let me wake you up.", "Sleep, friend. Close your eyes and sleep."},
    {"$animal_statue_physics", "Shall I take you to the other side?", "Death is not as bad as you might think.", "I can't claim to know more than you. But I am strong."},
    {"$animal_flamer", "Let me cauterize that wound, permanently.", "Having lungs must be awful. Breathing in so much smoke...", "Even after so long, the good ol' flamethrower still works..."},
    {"$animal_icer", "What will save you now? The heat of the sun? Ha.", "Don't breathe in the vapour, please. I've already won.", "Let me teach you about the art of the stunlock."},
    {"$animal_graham_fuzz", "We are stronger together!", "With our powers combined...!", "It's up to you now, friends!"},
    {"$animal_graham_wizard_familiar", "Ka-pow!", "I'm sure you feel perfectly enlightened after that.", "No fortune for you today, sorry."},
    {"$animal_coward", "Oh, this is SO much better than attacking indirectly.", "It seems so much simpler to just kill you myself.", "You know the saying. If you want it done right..."},
    {"$animal_ghoul", "I'm disappointed and disgusted.", "You've certainly faced creatures more acidic than me.", "Don't be dramatic."},
    {"$animal_icemage", "Your health will soon drop to absolute zero.", "Don't look so blue. Just try.", "Your death will be my gift this year."},
    {"$animal_statue", "Let me make your grave in my image.", "How pathetic. Look at your blood.", "Parry me, coward! I bet you can't."},
    {"$animal_assassin", "They always told me to not play with my food...", "I'm mechanical and tougher than you'll ever be.", "Diced and well-done, please."},
    {"$animal_drone_lasership", "I will extract all of your blood from your feeble body.", "It is a shame that you are not as flammable as wood.", "Lasers are so clean. No bullet holes at all."},
    {"$animal_miner_santa", "No coal for you. Although, would that hurt more...?", "Go make some snow angels. I insist.", "I know just what you deserve this holiday season."},
    {"$animal_cook", "You'll end up in my next-a recipe if you aren't careful!", "Social distancing. Stay a sausage's length away.", "Bah! Kids these-a days..."},
    {"$animal_lukki_tiny", "You're violent, but you're not hopeless... right?", "This is what you get! Stay away from our eggs!", "Your magic seems to be failing you..."},
    {"$animal_lukki", "You'll break as long as we just keep pushing.", "Where even do you belong...? Not here.", "You're an odd one. They usually go down easier."},
    {"$animal_lukki_longleg", "You may be as wise as us, but you're no saint...", "You know where you belong. Stay away from our lives.", "Just get out of here. One way or another."},
    {"$animal_bloom", "Hold your breath. Don't inhale the gas.", "Please move away so I'm not forced to start a fire.", "Hmm... I wish I could have hurt you more."},
    {"$animal_shooterflower", "It's funny to watch your dodging fail.", "Drop to the ground. Feel the grass.", "I mainly deal emotional damage... Idiot."},
    {"$animal_spearbot", "Good. I was constructed for a divine purpose.", "Your goals are unholy. Let yourself be cleansed.", "I am nothing by myself. What are you?"},
    {"$animal_boss_dragon", "My birthday is your deathday!", "You brought this upon yourself. Understand that.", "How much more of this can you take? Let's find out.", "Hmm... What makes you so durable? Magic? Or something more?", "If your home is not the jungle... Then you are not welcome in my lair.", "You're tough, but you'll break. I know it."},
    {"$animal_missilecrab", "Statistically, a few more missiles should cause your death.", "Be wary of the soot that such an explosion creates.", "Investing in homing rockets: a successful development."},
    {"$animal_healerdrone_physics", "It is against protocol to heal unauthorized users.", "Wasted ammo. Someone will have to pay for this.", "Simply delaying the inevitable."},
    {"$animal_lasershooter", "My gaze will not paralyze you, unlike some floating eyes I could mention.", "My field of view is bigger than yours, I assure you.", "No, I'm not crying! I just have something in my eye..."},
    {"$animal_worm_skull", "They're going to find you and you'll just be empty inside.", "Oh, I can sense potent magic within you...", "Your life... Give it all to me."},
    {"$animal_ghost", "Do you see me as a tick? I see you as a liability.", "Let's get this over with.", "Submit yourself to me. I could use a host..."},
    {"$animal_failed_alchemist", "I feel like... Something grander binds us together.", "I hate this. But this is where I belong.", "I'll break before you do. I'm sure of it."},
    {"$animal_failed_alchemist_b", "This is all my fault. But I can't...", "Make it stop. Make it stop!", "I'm such a disgrace. A shallow fascimile..."},
    {"$animal_enlightened_alchemist", "I can't hear you. There's this blaring in my mind...", "Stop breathing. Stop! I can't take it!", "I'll do whatever it takes to make the noise finally stop."},
    {"$animal_wraith", "What an interesting phenomenon.", "Hmm... This was not part of the plan.", "Unexpected, but not unwelcome."},
    {"$animal_wraith_glowing", "Look on the bright side. You're not dead yet.", "Perhaps death will help you appreciate your next life.", "Let's not pretend that this isn't a familiar feeling."},
    {"$animal_wraith_storm", "Maybe it would be wise to stay down this time.", "Haven't you learned anything at all?", "I'm surprised you can take any more of this."},
    {"$animal_skullrat", "Your flesh will go to the rats, and your bones will go to me!", "You'll wake up as a part of me as though nothing even happened.", "Don't worry, the only contagion I carry is death itself."},
    {"$animal_skullfly", "Heh. Don't panic... It'll just make your death more painful.", "I'll assimilate you once you die. Would you like that?", "My flames burn away the very essence of life that animates you."},
    {"$animal_crystal_physics", "Are you afraid of ghosts? Or what they can do?", "Stay awaaay! Haha!", "Who knows, maybe you'll turn into a ghost when you die, too."},
    {"$animal_lurker", "I'm a coalescence of everything you dread.", "You'll forever be cursed, one way or another.", "Don't look away... I'm everywhere you look."},
    {"$animal_lukki_creepy_long", "Be mindful of all that you don't have.", "Poke around and find out.", "Evidently, a head is just for convenience."},
    {"$animal_lukki_dark", "Yes, perish for me!", "Give me all of your delicious blood...", "Your blood, and then your corpse, all for me!"},
    {"$animal_worm_end", "Feel how strong these jaws are? Haha...", "I would say that I'll send you to hell, but... You're already here.", "I'll drag you even deeper down."},
    {"$animal_gazer", "When you die... Will you just end up back here?", "You've been trapped in a cycle of death this whole time.", "No mere mortal would venture here. What are you?"},
    {"$animal_skygazer", "My eyes will be the last thing you ever see.", "Nothing ends without death, but death is never the end.", "This isn't the first time that we've met... Is it?"},
    {"$animal_friend", "Something's bound to break inside you eventually.", "I won't give up until you're buried and dead.", "You certainly deserve this.", "I'll be satisfied once your run ends.", "I'm just doing this because I hate you.", "Your health is still too high for my tastes."},
    {"$animal_ultimate_killer", "Do you want a gourd?", "Welcome to our home!", "What's your name?"},
    {"$animal_thundermage_big", "How much charge can your feeble nerves even handle?", "I'm almost impressed that you're alive. Almost.", "What a crutch your magic abilities must be."},
    {"$animal_bloodcrystal_physics", "I feel like I'm trapped down here...", "You remind me of myself. That's a joke.", "What a horrible day to have a curse."},
    {"$animal_skycrystal_physics", "There's so much to explore... Why stay here?", "I sense an unholy presence... Is it you?", "What a horrible night to have a curse."},
    {"$animal_spitmonster", "Be grateful that I didn't bite you, at least.", "Your time's ticking down.", "This feels a bit futile..."},
    {"$animal_necrobot", "Some creatures just aren't worth the effort to save.", "Ah, it'll feel so good to truly kill something for once.", "Stay down this time. No resurrection for you."},
    {"$animal_necrobot_super", "Yeah, and don't try to use pheromone, either. Imbecile.", "Killing makes for quite good mental exercise.", "Why doesn't everyone have an energy shield? It helps."},
    {"$animal_minipit", "Nothing comes from nothing. You know this.", "Don't stop struggling. I'm having fun.", "This world is full of shadows..."},
    {"$animal_piranha", "There is no greater firepower than me around these parts.", "You had better learn the countermeasures to prevent this.", "Let's finish this."},
    {"$animal_shotgunner_hell", "Let down your guard for two seconds in here and everything will change.", "How many shields do you have? Not enough, it seems.", "It seems that I can still see better with this mask than you can."},
    {"$animal_sniper_hell", "A blood-red target's been painted on your head this whole time.", "All or nothing. Shall we duel?", "Turn away, lest I strike you in the eyes."},
    {"$animal_miner_hell", "You're still holding yourself together? Impressive...", "Ideally, you'd be gone once the smoke clears.", "No need to plan ahead. Every outcome ends up with someone dead."},
    {"$animal_graham_gasser_hell", "Don't be surprised if your lungs disintegrate sometime soon.", "If people knew what I made this gas out of, I'd be exiled.", "You could use a light dose of total organ failure."},
    {"$animal_drone_shield", "This is a very strange situation we find ourselves in.", "Error: How did this happen.", "Do I now... Apologise?"},
    {"$animal_hidden", "Nothing personal, kid.", "Boo! Jumpscare!", "How embarrassing. For you, I mean."},
    {"$animal_soldier", "Consider it an honour to perish to my weaponry.", "I believe something called \"dodging\" may help you in this situation.", "Off with your head!"},
    {"$animal_neutralizer", "I had to ask very politely to be given this secondary fire.", "It would be dishonest to claim this is not a personal attack.", "You must not be very happy about this scenario."},
    {"$animal_sentry", "The blinking lights are very necessary. I would not lie.", "I am proud to live in an extremely secure area.", "The whole world is against you now."},
    {"$animal_ethereal_being", "It all returns to nothing eventually.", "Let me into your head. I need to know...", "It would be a shame if something happened to your magic..."},
    {"$animal_fish_giga", "Drown.", "Reconsider. Your death awaits.", "This encounter shall be your last.", "Your corpse will be snatched up by the eels soon enough.", "Close your eyes. It's best if you don't see it coming.", "I tire of wasting my time with you."},
    {"$animal_boss_limbs", "We can forget your transgressions. Just let yourself go...", "Do you know how many are a part of me now? Too many to count.", "Believe me, this isn't over quite yet.", "You think I can't feel every single thing you do to me?", "Perhaps I can go back and rest after you die.", "Some strange new diseases might rot your body soon. How fun."},
    {"$animal_slimeshooter_boss_limbs", "Don't think too much about what happens next.", "It's just recycling. Or something like that.", "Acid is so wasteful. Corpses can be valuable."},
    {"$animal_chest_leggy", "You seem to be at a loss for words. I understand.", "It's not every day you meet someone as amazing as myself.", "Let me educate you on how amazing this mutation can be."},
    {"$animal_fungus_tiny", "Goodbye.", "Boop.", "I got you."},
    {"$animal_fungus_tiny_perk", "What is this!?", "Quite interesting...", "Aargh."},
    {"$animal_mini_mimic", "Chomp. Chomp.", "I got ya!", "Rraaah!"},
    {"$animal_bloody_mimic", "Bleed.", "You fool...", "I will mutilate you."},
    {"$animal_homunculus", "Oh, my bad! Jeez...", "Youch! That's gotta hurt...", "N-no hard feelings, right, boss?"},
}

---@type string[][]
DIALOGUE_DAMAGETAKEN = {
    {"$animal_shotgunner", "Augh!", "You'll pay for that!", "That hurts..."},
    {"$animal_zombie", "Leave me...", "This is my end.", "Are you hungry too?"},
    {"$animal_chest_mimic", "Hey! Knock it off!", "Shh, you'll ruin the disguise!", "Stop it, I'm hiding!"},
    {"$animal_dark_alchemist", "This disguise usually works... What a shame.", "Damn. Maybe I'll get you next time.", "Fine, then. I'll remember this."},
    {"$animal_shaman_wind", "This disguise always works! What gives?", "Damn it! You found me!", "Fine, then. I'll kill you next time."},
    {"$animal_longleg", "You are weak!", "Ahh!", "Fight us!"},
    {"$animal_miner", "I'll blow you to pieces!", "Bring it on!", "Beware!"},
    {"$animal_firemage", "You want to go? Let's go!", "Your health looks a bit too high. Mind if I help?", "Ever heard the myth about boiling the frog?"},
    {"$animal_firemage_weak", "You'll need more than that to take me down.", "That hurts... a little bit.", "Who do you think you are?"},
    {"$animal_slimeshooter", "Just wait 'til my mom hears about this!", "If I was able to spit acid instead, you'd be screwed!", "Splat!"},
    {"$animal_acidshooter", "Look into my eye!", "Keep your distance.", "I'll corrode you down to nothing."},
    {"$animal_giantshooter", "My children...", "If I were you, I wouldn't!", "See what good killing me will do for you."},
    {"$animal_frog", "I'm just a little frog...", "Owie!", "Hey, that hurts!"},
    {"$animal_frog_big", "That's unfortunate.", "I don't blame you.", "Is this necessary?"},
    {"$animal_miner_fire", "I'll get my revenge.", "I hope you burn.", "How dare you!"},
    {"$animal_graham_miner_gasser", "My gas is stronger than sludge. Take my word for it.", "If only this suit protected from more than just toxicity...", "Now you're starting to annoy me."},
    {"$animal_boss_pit", "You came here just to challenge me?", "You're an utter fool!", "I'm still alive, which means that you've not done your job properly.", "What, do you want it to be a fair fight? Ha ha ha.", "Go jump in the lava lake.", "Am I the strongest opponent you'll face? That's sad."},
    {"$animal_shaman", "I won't forgive you for this.", "Step back, child...", "Stormy skies await you."},
    {"$animal_playerghost", "Do you see your reflection in me?", "Don't feel guilty. This isn't my first time dying.", "I see potential in this one. Good luck..."},
    {"$animal_firebug", "You'll regret this.", "There's always an ally behind me, I'm sure of it.", "Backup! Hive, I need backup!"},
    {"$animal_bigfirebug", "I'll turn you into ash for that!", "The Hive never forgets.", "Perish!"},
    {"$animal_fireskull", "I'm after you.", "Get over here!", "Argh!"},
    {"$animal_bat", "I'm coming for you!", "No!", "I'll take one for the team!"},
    {"$animal_bigbat", "Be slowed to a crawl.", "Soon enough, you'll be swarmed.", "Mmhmm..."},
    {"$animal_sniper", "I could end your life with my eyes closed!", "Hey, that one almost hurt.", "You know that I'm going easy on you, right?"},
    {"$animal_scavenger_grenade", "Do your worst!", "I think I broke something...", "H-hey, is there a healer nearby? Help!"},
    {"$animal_thundermage", "I'm as tough as diamonds! Just try me!", "Don't let your guard down, fool. I can still blast you to pieces.", "Don't get cocky. One slip-up, and you're done for!"},
    {"$animal_goblin_bomb", "Oh, noo!", "I changed my mind! Leave me alone!", "No, no!"},
    {"$animal_scavenger_heal", "Show some respect!", "Hey! Don't be mean!", "B-but... There's still so many more people that need healing!"},
    {"$animal_boss_alchemist", "You should join us... We lack someone with your willpower. Heh heh heh.", "Faceless and nameless... You remind me of myself.", "Come closer. Let me get a good look at you.", "Don't look at me like you know me. It's offputting.", "Did the sight of my underlings upset you? Trust me, you haven't seen the half of it.", "I'll be missed if someone ends my life. Can you say that for yourself?"},
    {"$animal_parallel_tentacles", "Although I'm just a husk... I can end you all the same.", "It would be so easy to just give up now.", "Some day I'll come out from under you."},
    {"$animal_parallel_alchemist", "Life without living... Is that what you seek?", "You're already a shadow of who you once were.", "You can't put me back together. So end it."},
    {"$animal_wizard_poly", "This is why I like sheep more than people.", "Hurt me all you want, I'm unstoppable!", "You won't find me so helpless once I polymorph you!"},
    {"$animal_wizard_dark", "Too bright...", "Watch your blind spot.", "I wish you would just disappear."},
    {"$animal_wizard_tele", "You can't stop chaos's reign!", "Teleport away, now!", "I didn't know that that ring of teleportitis was cursed..."},
    {"$animal_wizard_returner", "You just wait 'till I fire that right back!", "Wanna play tennis? Back, forth, back, forth...", "Imitation is the sincerest form of flattery."},
    {"$animal_wizard_swapper", "Can't catch me!", "You're too slow!", "Uahaha!"},
    {"$animal_wizard_neutral", "NULL_EXCEPTION.", "Czzzt!", "L-let's go to commercial."},
    {"$animal_wizard_twitchy", "Mm-h!", "Y-you w-won't miss me.", "Y-you're just j-jealous that I'm faster..."},
    {"$animal_wizard_hearty", "Urgh... My blood, my blood...", "Salt in the wound.", "At least I don't try to hide it."},
    {"$animal_wizard_weaken", "I'm already over it.", "Nothing I can say will convince you to stop.", "Perhaps you know better than I do."},
    {"$animal_wizard_homing", "I hope you're not using homing. That'd be hypocritical.", "I see a few ways this could go.", "Well, that's just rude."},
    {"$animal_barfer", "Yeow! Keep that thing away from me!", "H-hey! Stop that!", "H-haven't you heard? T-treat others as you... O-ow..."},
    {"$animal_necromancer_shop", "Oh, you'll pay for that one!", "It'll only get worse for you if you resist!", "I would have loved to get to know you better, in different circumstances."},
    {"$animal_necromancer_super", "You may have taken down our, ahem, lesser guards, but it's not over.", "The Gods never forget your sins.", "Face it. You're in way over your head on this one."},
    {"$animal_roboguard", "Don't resist!", "Stand down, magic-user!", "You've messed with the wrong robot!"},
    {"$animal_scavenger_invis", "That's rather mean, isn't it?", "Out of sight, out of mind.", "Give it up, seriously..."},
    {"$animal_scavenger_shield", "Why can't we all just get along?", "Spare my life, please?", "I really just wanted to help people..."},
    {"$animal_alchemist", "You can't handle my strongest potions.", "Hey, I don't know anything about 'em. I just throw 'em.", "Is this revenge for the acid potion?"},
    {"$animal_tentacler", "I hope you can do better than that peashooter.", "You're funny. Get closer so I can end your life.", "Doesn't sting at all."},
    {"$animal_tentacler_small", "You're such a pain!", "I may be small, but I can pack a punch!", "Get a bit closer, then you'll see...!"},
    {"$animal_ant", "Can't you handle a little corrosion?", "I understand if you're afraid...", "I suppose I'm not the first bug you've squashed."},
    {"$animal_maggot", "Sorry... I know it's hard to aim around me.", "I'm not trying to get in your way.", "I'm just a bug... Perhaps a bit larger than most."},
    {"$animal_fungus", "Wah!", "I don't know much...", "Time's running out."},
    {"$animal_fungus_big", "Get over here!", "I've heard about you through the grapevine...", "Death is just temporary when you're like us."},
    {"$animal_fungus_giga", "Just a little bit off the top, thank you.", "Hehe... you're short.", "I'm too dignified to self-destruct, don't you know?"},
    {"$animal_fly", "That's fine... I'll be fine.", "Just please don't touch our honey...", "It'll all be worth it in the end..."},
    {"$animal_drone", "I've already informed my correspondents of your location.", "Mayday! Mayday!", "Risk levels high. Please respond..."},
    {"$animal_bigzombie", "Ouch... are all my limbs still attached?", "Don't get a-head of yourself.", "Oh, you haven't heard the last of me."},
    {"$animal_bigzombiehead", "My back pain... it's cured!", "That's giving me a headache.", "I can still bite you, even while my teeth rot away!"},
    {"$animal_rat", "Don't hate us...", "You're so mean.", "Brothers, help!"},
    {"$animal_iceskull", "Chill out, dude!", "Cool it! I don't like your attitude.", "I knew you weren't cool."},
    {"$animal_thunderskull", "You can't handle the sheer volts I'm outputting.", "You're no fun.", "No frozen skulls can compare to my sheer power."},
    {"$animal_giant", "Giving up would be so simple.", "You're quite a disappointing one.", "Echo, echo, echo..."},
    {"$animal_scavenger_mine", "What a problem you are.", "I kill for sport. Can't say the same for you...", "What's wrong with you?"},
    {"$animal_scavenger_glue", "Stick around for the fight of a lifetime!", "Oh, get me out of this horrid place...", "I'm not helpless, you know."},
    {"$animal_scavenger_leader", "Drinks are on the house for whoever kills that thing!", "I swear, I will END you.", "What do I pay you fools for? Get them!"},
    {"$animal_scavenger_smg", "O-on second thought, maybe being a janitor isn't so bad...", "I would offer you a truce, but the boss would get mad...", "You won't make it past me unscathed!"},
    {"$animal_scavenger_clusterbomb", "That makes me furious.", "I don't have any sympathy left for you.", "Now I only want you gone."},
    {"$animal_scavenger_poison", "You're such a vile creature.", "You make me sick.", "Disgusting."},
    {"$animal_tank", "Fatal error: Divided by zero. Rebooting...", "Don't you dare touch my CPU.", "I lagged! What happened?"},
    {"$animal_tank_rocket", "Oil is expensive these days. What a waste...", "Buffering... buffering... ouch.", "Something I am doing is wrong. That is what pain tells me."},
    {"$animal_tank_super", "Statistically, you will not like what happens next.", "It seems we have a pest problem. Resolving...", "My armour is as tough as your entire body."},
    {"$animal_turret", "Oh dear.", "Critical error.", "Help me, I'm running on Javascript."},
    {"$animal_miniblob", "Pain!", "Hurt!", "Irk!"},
    {"$animal_blob", "Disperse! Now!", "Divide! Conquer!", "Go! Soldiers!"},
    {"$animal_necromancer", "At least kill me with an interesting wand this time.", "Frankly, I'm a bit disappointed...", "Sigh... just make it quick."},
    {"$animal_monk", "It's all for you. Ungrateful brat.", "I see you behind the screen. Look at you.", "This is what happens when us monks don't educate people like you."},
    {"$animal_worm_tiny", "I'll leave you alone now! P-promise!", "I won't damage anything here, trust me!", "Waaah!"},
    {"$animal_worm", "Fine, fine! I won't break your brickwork anymore.", "I'll get you back for that one.", "Hey, flying is cheating! Stay on the ground like me."},
    {"$animal_worm_big", "Hey! Hands off the hide.", "Are you jealous of my beautiful sight?", "Just let me do my thing, and I'll leave you be."},
    {"$animal_phantom_a", "I cannot believe you thought that'd kill me.", "You can't kill a ghost, idiot.", "I'll tear you into little tiny bits!"},
    {"$animal_phantom_b", "You may regret this decision.", "Let me be clear. I dislike you.", "You'd better start spinning."},
    {"$animal_statue_physics", "Please, remove this curse...", "You can't stop what has begun.", "Let me take one last breath."},
    {"$animal_flamer", "This ain't a helmet. It's just my head. Hands off.", "I'll enjoy watching you burn.", "Ashes to ashes..."},
    {"$animal_icer", "You look like you'd be scared of the word \"propane\".", "Where's the AC in here? It's too freakin' hot!", "No, not the oil! I don't want to start a fire!"},
    {"$animal_graham_fuzz", "Oh, you just wait until I pop...!", "H-hey, wait! Shouldn't you attack the other enemies first?", "Your projectiles are nothing to me! Haha!"},
    {"$animal_graham_wizard_familiar", "I know you can handle a little bit of fun.", "Receive my wisdom, you... dummy.", "Slow down a bit. It could save your life someday."},
    {"$animal_coward", "I'm just doing my job. No need to be hostile.", "I should've invested in a better shield...", "You're a coward!"},
    {"$animal_ghoul", "I'm running out of ribs to break...", "You're gross and non-slimy.", "Blah! Don't even try it!"},
    {"$animal_icemage", "I'm a bit chilly myself...", "My skull can hardly take this beating.", "You wish I was as fragile as ice."},
    {"$animal_statue", "You're not the only one to remember their past lives.", "Do you ponder your own purpose? I do.", "You're lucky. There's only one of you."},
    {"$animal_assassin", "You're slicing up my patience...", "Ask Stendari if he wants to cook with me sometime, yea?", "I'm not one to complain, but..."},
    {"$animal_drone_lasership", "I appear to have sprung a leak.", "I hope you do not start a fire.", "I wish I could just fall down and crush you."},
    {"$animal_miner_santa", "Five more years of the Naughty List for you!", "You won't find any presents underneath your tree this season.", "I ain't no faker. Keep your hands off of me."},
    {"$animal_cook", "I bet-a your corpse would go well with oregano...", "It won't all be sugar and spice if you keep doing that.", "A chef can poison-a food like no other, you know..."},
    {"$animal_lukki_tiny", "No! Not you, not now...", "Such violence... please leave us alone.", "I see why the elders say bad things about you..."},
    {"$animal_lukki", "Change is hard. I know that as well as anyone.", "Please, think about this...", "I'm gonna go eat some brickwork if you don't stop."},
    {"$animal_lukki_longleg", "I wouldn't want to coexist with someone like you anyway.", "How childish. Have some respect towards your elders.", "That attitude is bound to come back to you one day."},
    {"$animal_bloom", "How could you hurt such an innocent little flower?", "Something within you... chills me to my core.", "Maybe you can turn me back into a normal flower."},
    {"$animal_shooterflower", "Leave me be. I'll fade into the background soon enough.", "Don't you have bigger things to worry about?", "If only I knew that I would have my sentience robbed by you."},
    {"$animal_spearbot", "I do not know where you belong... but it is not here.", "Blasphemous being. What would your gods think?", "My body is not fragile, but my patience is."},
    {"$animal_boss_dragon", "You'll pay for disturbing my slumber!", "Stay away from my jaws. Last warning.", "You're in my lair now, and this dragon hoards no gold.", "I won't give up. No matter how strong you may be...", "Ha! Perhaps I've finally met someone as stubborn as myself!", "I'll get to you eventually. Keep running."},
    {"$animal_missilecrab", "This scenario should not happen. Error logged.", "You are a variable that has not been accounted for.", "Let us see whose health will drop to zero first."},
    {"$animal_healerdrone_physics", "This does not seem beneficial to you.", "Is your purpose to simply remove all other sentient beings?", "Have you no respect for our work?"},
    {"$animal_lasershooter", "You are, by far, the strangest thing I've seen recently.", "I'll win any staring contest that you challenge me to.", "I would ask you to aim around my eye, but..."},
    {"$animal_worm_skull", "Try it all you'd like. You won't make a dent.", "Perhaps I overestimated you. Or is it something else...?", "I have bigger things to worry about."},
    {"$animal_ghost", "You truly are a damned creature.", "Well, that's new.", "How ironic... No, not really."},
    {"$animal_failed_alchemist", "Death is not an escape. It's just another hell...", "There's no going back this time.", "You won't make things any worse... Even if you try."},
    {"$animal_failed_alchemist_b", "It doesn't even hurt anymore, it just...", "I don't want to suffer any more.", "Wake me up. I want to wake up...!"},
    {"$animal_enlightened_alchemist", "I'm scared of the other side, so please...", "All of my senses are burning away.", "Count the sunsets. You only have so many of them left."},
    {"$animal_wraith", "Heh. That tickles.", "This might take a while.", "That's not a particularly wise thing to do."},
    {"$animal_wraith_glowing", "Oh, it's on...!", "Are you challenging me? Let's go, then!", "You really want to do this? Your funeral."},
    {"$animal_wraith_storm", "Your ascent will lead you to somewhere wicked, I know it.", "You think you're so clever, don't you?", "This was all predestined. Where will it go...?"},
    {"$animal_skullrat", "I don't see what's so unholy about reanimation.", "Maybe I'll manage to hold myself together this time.", "I can feel everything falling apart again..."},
    {"$animal_skullfly", "Oh, you think you're better than me, do you?", "You can't kill me in a way that matters.", "How do I speak with no jaw? Magic. That's all."},
    {"$animal_crystal_physics", "Try it! I can always choose a new crystal.", "There are enough gems around here to sustain me for eternity.", "Hey, hands off! This one's occupied!"},
    {"$animal_lurker", "This bubble isn't going to pop just yet.", "Spread this essence of darkness far and wide...", "What lead you to this point? Do you regret it?"},
    {"$animal_lukki_creepy_long", "What a cruel creature you are.", "I speak with no mouth... You fight with no concience.", "So rude... My friends will eat you right up."},
    {"$animal_lukki_dark", "Your spells won't stop the hunger!", "You think you can take me on?!", "You're fighting a losing battle!"},
    {"$animal_worm_end", "What's hell for you is like heaven for us.", "My blood boils at the thought of you living any longer.", "You dare to assault a creature like me?!"},
    {"$animal_gazer", "Face it. You never had a choice.", "You don't know a thing...", "Isn't this where you belong?"},
    {"$animal_skygazer", "The choice has been yours all along.", "I know you more than you know yourself.", "You must be horribly lost to end up here."},
    {"$animal_friend", "Do what you want. Just don't hurt the little ones any more.", "You should've gone down a different path...", "Next time, I'll hide this damn cave better.", "What a horrid creature you are. Really now.", "I will never forget the things you've done.", "Anger... Pure anger."},
    {"$animal_ultimate_killer", "Ow! That hurts!", "Hey! You're a meanie!", "I don't like you..."},
    {"$animal_thundermage_big", "You WISH that you could fire my projectiles from your puny little wands.", "Yeah, I'm not gonna let that slide. Not a chance.", "One punch and your whole body would be entirely paralyzed."},
    {"$animal_bloodcrystal_physics", "It's too warm in here... Ice hurts.", "The crystals don't mean anything! Us ghosts are all magic.", "Careful not to get your blood mixed up with my sheen."},
    {"$animal_skycrystal_physics", "Don't even try to set me on fire.", "All types of crystals have latent magical properties.", "\"Poltergeist\" tends to have quite a negative connotation..."},
    {"$animal_spitmonster", "You came all this way just to do this?", "If you were in my place, would you abandon hope?", "It ain't over until someone's health drops to zero."},
    {"$animal_necrobot", "No need to worry. My metal is reinforced three times over.", "Death is no large event. Everyone else is so dramatic.", "Perhaps my components can be repurposed after I die."},
    {"$animal_necrobot_super", "At least it's not that awful mana liquid...", "Get away! You're gonna smudge my screen.", "Do you really think that I care?"},
    {"$animal_minipit", "You don't know what you've gotten yourself into, do you?", "Please don't compare me to a meatball.", "You can't make this situation any worse."},
    {"$animal_piranha", "You are making a serious mistake.", "I'm not the only thing here that can tear you to pieces.", "A bit of electricity is nice... Too much is lethal."},
    {"$animal_shotgunner_hell", "This must be what true despair feels like.", "What do you expect? I won't just lie down and die.", "I'll struggle against you until the bitter end."},
    {"$animal_sniper_hell", "Please leave my eyes intact, at the very least.", "There are no words to express my rage...", "Let me teach you a new definition of pain."},
    {"$animal_miner_hell", "Layers and layers of skin to shed...", "It doesn't get much worse than this.", "I manage to stop the bleeding... Most of the time."},
    {"$animal_graham_gasser_hell", "Don't punch a hole in my suit. You'll regret what happens next.", "The blood flows through the eye holes. Looks like I'm crying.", "More blood to brew up my bottles."},
    {"$animal_drone_shield", "If you get polymorphed, I will keep you safe.", "I have been instructed to not protect anyone that looks like you.", "Can you not find ways to solve problems without hostility?"},
    {"$animal_hidden", "I suppose I should not have expected anything more from you.", "Electricity merely charges my invisibility. Do not try it.", "Can we do a do-over? Let my invisibility recharge..."},
    {"$animal_soldier", "An .exe will not execute me, despite the name.", "Who are you? No one executes the executioner.", "I hope you did not expect me to avoid that."},
    {"$animal_neutralizer", "My shell is standard-issue. Nothing special around here.", "This place absorbs far more power than it outputs.", "I will do my job until the day that I am decommissioned."},
    {"$animal_sentry", "The only spies permitted here are those on our side.", "You're not invisible, but I do not wish to look at you any longer.", "It pays to observe. Data collection is rather profitable."},
    {"$animal_ethereal_being", "You bring me back just to dismiss me again?", "I guess this is what I get for trying to influence you.", "You deserve far worse than anything you could do to me."},
    {"$animal_fish_giga", "Curse you and everything that you stand for.", "Don't forget the past. The portals never close.", "I would gladly disembowel you... If I was capable.", "You have no idea what's truly worthwhile in this world.", "Your eyes don't seem suited for environments such as this...", "Things will never truly be normal again, will they?"},
    {"$animal_boss_limbs", "I'm not the only one with darkness lurking inside.", "The heart always beats until it forever stops.", "We all had names. Identities. All forgotten, now.", "I have followers. Friends. They will never forget me.", "I accepted my fate a long, long time ago.", "Don't ignore your weaknesses. That's how the end comes."},
    {"$animal_slimeshooter_boss_limbs", "Do what you want. You can't stop us.", "Try to catch up before the corpses rot away.", "Just one skull can make all the difference."},
    {"$animal_chest_leggy", "Oohoho! Care for a dance?", "Join the fun with me!", "I've got a gift for you..."},
    {"$animal_fungus_tiny", "Time's up.", "Squash. Pain...", "I'm bleeding. How fun."},
    {"$animal_fungus_tiny_perk", "Oh, my time is now...!", "I can't take much more of this...", "I feel dizzy..."},
    {"$animal_mini_mimic", "Aw... Just this once?", "I'll pick a better hiding spot... Next time.", "Ow! So mean..."},
    {"$animal_bloody_mimic", "Blood craves blood.", "Argh... You...!", "Look away or I'll bite out your eyes."},
    {"$animal_homunculus", "Hey! I haven't done that bad of a job, have I?!", "Ouch... Sorry, boss. I'll do better.", "My bad... I should've dodged that."},
}

---@type string[][]
DIALOGUE_IDLE = {
    {"$animal_shotgunner", "Who are you?", "I want to take a nap.", "This is my territory!"},
    {"$animal_zombie", "Hungry... so hungry!", "Must feed...", "Where are you?"},
    {"$animal_chest_mimic", "...", "...?", "...!"},
    {"$animal_longleg", "Strong in numbers...", "Weak in strength...", "Where's food?"},
    {"$animal_miner", "Need me to dig a hole?", "Where did everyone go?", "Friend?"},
    {"$animal_firemage", "It's a big compliment, to be the hottest color of fire.", "What's the melting temperature of steel? Oh, no...", "I'm not afraid of water! I just... don't like it."},
    {"$animal_firemage_weak", "The fire is so calming...", "Does anyone have a tablet? They don't burn in my hand like books do.", "Not much for conversation, eh?"},
    {"$animal_slimeshooter", "Cleansing sludge...", "I wish I could spit acid.", "Gurgle, blop."},
    {"$animal_acidshooter", "I see you.", "I can see you through the dark.", "Death is near!"},
    {"$animal_giantshooter", "Bloated...", "Ugh...", "What was that?"},
    {"$animal_frog", "Ribbit.", "Hop, hop.", "Meow."},
    {"$animal_frog_big", "Robbit.", "Skip, jump.", "Woof."},
    {"$animal_miner_fire", "I'll burn this whole place down!", "Don't look at me like that!", "You're flammable! All of you!"},
    {"$animal_graham_miner_gasser", "Don't worry, I kill cleanly.", "I can singlehandedly lower the air quality by over " .. tostring(Random(25, 99)) .. "%.", "Am I really the most level-headed one here?"},
    {"$animal_boss_pit", "I know you're here. Show yourself!", "A coward. You are a coward!", "Power corrupts. We both know that well.", "One of these days... I'll cast a black hole and burrow my way out of this place.", "I enjoy reading as well as obliterating unwise explorers.", "What, do you expect me to make small talk?"},
    {"$animal_shaman", "No one really knows...", "Will you remember me?", "Hm? Oh, it's nothing..."},
    {"$animal_playerghost", "Where have I gone? This isn't my world...", "Risen from my grave... I'll soon return to it.", "I feel lost... am I truly the only one?"},
    {"$animal_firebug", "Bzzt...", "We serve the Hive...", "Regroup and prepare to swarm."},
    {"$animal_bigfirebug", "Bzzt!", "I must protect the Hive!", "I can handle it by myself!"},
    {"$animal_fireskull", "I smell smoke!", "I'm comin' for ya!", "Heeheehee..."},
    {"$animal_bat", "Flap, flap, squeak...", "Blah...", "I'm craving something sweet."},
    {"$animal_bigbat", "Will my children ever get the chance to grow up...?", "Peace and quiet, please?", "I'm craving something salty."},
    {"$animal_sniper", "I'll strike you down... whether you're close by or far away.", "I know you're there. Don't try anything funny.", "...I'm not just talking to myself here, am I?"},
    {"$animal_scavenger_grenade", "I should go get a drink after this...", "What day is it? I think rent's due soon...", "I need more coffee..."},
    {"$animal_thundermage", "My clothing? It's custom-made, thank you very much...", "If you can hear my electric crackle, you're too close.", "Magic keeps me alive... and makes so many other things dead."},
    {"$animal_goblin_bomb", "Hrmm...", "Shiny, sparkly glitter...", "What was that sound?"},
    {"$animal_scavenger_heal", "Does anyone need healing?", "I love my job.", "This place could really use some cleanup..."},
    {"$animal_boss_alchemist", "Wonders you can't have...", "And yet, there's something missing.", "Is my vision failing me? Or...", "I sense that you're nearby. Do you seek enlightenment?", "Let's make this quick, then.", "If only things went differently, so long ago..."},
    {"$animal_parallel_tentacles", "I feel our reality ripping at the seams...", "I see no evil, and yet evil remains.", "Three eyes count down to one. Then the whole world goes dark."},
    {"$animal_parallel_alchemist", "It'll all be torn apart if this doesn't stop...", "Where are our Gods now?", "The end is near."},
    {"$animal_wizard_poly", "Pink is my favourite colour.", "My flock is looking a bit small...", "Stay back, I'd rather not get blood on my robe..."},
    {"$animal_wizard_dark", "Purple is my favourite colour.", "Where have you gone?", "Something else lurks beyond."},
    {"$animal_wizard_tele", "Yellow is my favourite colour.", "Peekaboo!", "Instability is my specialty."},
    {"$animal_wizard_returner", "Cyan is my favourite colour.", "Fun fact: It is impossible to outrun your own reflection.", "I see you staring. I'm staring back."},
    {"$animal_wizard_swapper", "Blue is my favourite colour.", "Who's ready for some shenanigans? You better be!", "It's all just a game! Why not have some fun with it?"},
    {"$animal_wizard_neutral", "Silver is my favourite colour.", "Have you tried turning it off and on again?", "Biological... technological..."},
    {"$animal_wizard_twitchy", "Green is my f-favourite colour.", "H-hard to focus... hard to s-stay still.", "Everything's o-out of control..."},
    {"$animal_wizard_hearty", "Red is my favourite colour.", "What? A helmet? Why would I wear a helmet?", "Do you think I look gross? That's rude."},
    {"$animal_wizard_weaken", "White is my favourite colour.", "What's behind the mask? ...Stay in your own lane.", "Perhaps I look just like you, down below. Or perhaps not."},
    {"$animal_wizard_homing", "Crimson is my favourite colour.", "Don't touch my head.", "Don't call me self-absorbed!"},
    {"$animal_barfer", "M-my favourite color is... o-oh, I don't remember...", "H-hurp... I feel terrible...", "They kicked me out because I p-puked on a tapestry..."},
    {"$animal_necromancer_shop", "Who dares desecrate the Gods' holy land?!", "Let's make this quick... I have a meeting soon.", "If anyone moves these statues around, I'm gonna be mad!"},
    {"$animal_necromancer_super", "I may have skipped leg day, but I'd never skip arm day.", "I'd prefer not to waste any more time on something like this.", "You've made your mistakes. Time to face the consequences."},
    {"$animal_roboguard", "Tonight is movie night...", "Those thunder mages always seem to evade the law...", "I'm still a bit human inside, I promise..."},
    {"$animal_scavenger_invis", "...What, would you rather hide under a cardboard box?", "C'mon, people, get those stains off!", "Stealth technology is constantly improving..."},
    {"$animal_scavenger_shield", "Protect the world from devastation!", "Let's just stop all this fighting, okay?", "Temporary shields complement permanent shields very well, don't you know?"},
    {"$animal_alchemist", "Hey kid, want some potions?", "I call them flasks, because they're not all magical...", "How do I get them 200% full? A magician never reveals their secrets..."},
    {"$animal_tentacler", "I can easily shatter ice with a single strike.", "I used to dwell in the ocean... Until magic changed me.", "A swift slap often knocks the confidence out of someone."},
    {"$animal_tentacler_small", "Nothing to see here...", "When's lunch?", "One day I'll be big and strong."},
    {"$animal_ant", "I have an iron stomach, you know.", "There's nothing that a little bit of acid can't fix.", "It's bubbling up inside..."},
    {"$animal_maggot", "Oof, I got heartburn...", "Would it be weird if I kept a smaller maggot as a pet?", "I'm less scary than I look. ...Do I look scary?"},
    {"$animal_fungus", "Skitter, scatter...", "The roots run deep.", "Rambling, shuffling..."},
    {"$animal_fungus_big", "It'll all return to soil...", "Muddy thoughts...", "Smells bad in here..."},
    {"$animal_fungus_giga", "It's blooming season...", "Don't touch me.", "The fungi speaks to us..."},
    {"$animal_fly", "I hope that no one's melee immune around here.", "That divine liquid... we just need diamond now.", "Need pollen... are there any flowers nearby?"},
    {"$animal_drone", "Air conditions nominal; Good flight conditions.", "Everything is going according to plan.", "Scouting potential routes..."},
    {"$animal_bigzombie", "Don't be scared of death. Just look at how I turned out.", "You've no stress at all, once you've already died.", "Necromancy is quite a fun game to play."},
    {"$animal_bigzombiehead", "Oh, now you've done it.", "I'm dead...", "Onwards and upwards..."},
    {"$animal_rat", "I wanna eat the moon.", "Leave this place!", "No one ever tries to sympathize."},
    {"$animal_iceskull", "I'm just a laid-back kind of dude, you know?", "Everyone around here just wants to copy my style...", "I'm way cooler than any electric skulls around here!"},
    {"$animal_thunderskull", "I'll power your electronics if you pay me.", "My taste in music? Nothing but metal.", "Bzzzt! Ain't that shocking?"},
    {"$animal_giant", "Think again about what you consider natural.", "The line between living and nonliving is often unclear.", "You know not what forces allow you to survive."},
    {"$animal_scavenger_mine", "Did I forget to renew my hunting license?", "I hope landmines are legal around here.", "Don't mistake me for a healer again."},
    {"$animal_scavenger_glue", "Anyone wanna hire a distraction?", "I will legitimately kill you if you try to eat my glue.", "I hope this place doesn't smell as bad as I imagine it does."},
    {"$animal_scavenger_leader", "Can I get a status report?", "Keep an eye out, there could be intruders anywhere...", "There's so much work to do... no time to think."},
    {"$animal_scavenger_smg", "I stuff this outfit with extra bullets when the boss isn't looking.", "I'm glad I'm not on cleaning duty.", "Remember your training... no hesitation, don't think twice."},
    {"$animal_scavenger_clusterbomb", "At least I didn't get stuck with the poison gun...", "Avoiding collateral damage is hard when everything is so flammable.", "Outta the way! I have places to be, you know."},
    {"$animal_scavenger_poison", "At least I didn't get stuck with the grenade launcher...", "To be honest, I never really liked this place.", "There probably aren't any long-term health risks of poison gas."},
    {"$animal_tank", "Problems detected. Rebooting...", Random(3, 50) .. " errors detected. Resolving...", "Does anyone know the internet password?"},
    {"$animal_tank_rocket", "Do not look directly into the barrel.", "Metal can outlast any creature of flesh.", "What do you think you are?"},
    {"$animal_tank_super", "My bullets are magic. My shell is steel.", "No worries at all about overheating.", "I can fire grenades as well. For some reason."},
    {"$animal_turret", "Is anyone there?", "Minimal activity detected.", "Sentry mode activated."},
    {"$animal_miniblob", "Swarm, swarm!", "Infest!", "More, faster!"},
    {"$animal_blob", "Increase numbers...", "Multiply, more...", "An infestation!"},
    {"$animal_necromancer", "No, they're not cat ears. Weirdo.", "Can we get some variety in here? I'm so bored.", "Tablet-kicking is, like, so last-week."},
    {"$animal_monk", "You creatures of nature are so ignorant without us.", "I was designed to educate... one way or another.", "If I don't do my job, something else might."},
    {"$animal_worm_tiny", "This is interesting...", "I'm outta here!", "New day, new experiences!"},
    {"$animal_worm", "Worm.", "Carve your own path, that's my motto!", "Just keep movin' forward..."},
    {"$animal_worm_big", "Don't ask where I'm going, 'cause I have no idea!", "I'm not lost... Everywhere is my domain!", "I'm on tour, haven't you heard? Gotta keep moving..."},
    {"$animal_phantom_a", "I bet you guys wish you had as many eyes as I do.", "Mind your own business! All of you!", "I need to take my anger out on something..."},
    {"$animal_phantom_b", "Yes, it's weird for a ghost to have hair. Shush.", "Fear that which goes bump in the night.", "Don't turn on the lights."},
    {"$animal_statue_physics", "Did someone here pick up a cursed key or something?", "Just let me rest...", "Don't look at me."},
    {"$animal_flamer", "Air conditioning? Why would I ever want to make things colder?", "Cleaning up blood is such a hassle.", "If any of you bring a fire extinguisher in here, I swear...!"},
    {"$animal_icer", "Four eyes is better than two.", "No, propane tanks don't home towards you. Though that would be funny.", "Why isn't that mana liquid freezable? What a pain..."},
    {"$animal_graham_fuzz", "I hold the power of plasma! But only a little bit...", "Sometimes you just need a little push to reach greatness.", "When I grow up, I want to be a plasma ball."},
    {"$animal_graham_wizard_familiar", "Mint is my favourite colour.", "I'll give you some orbs to ponder.", "Don't stare for too long."},
    {"$animal_coward", "If I throw a party, I'm making you guys come to it.", Random(23,45) .. " lonely Hiisi have been detected in your area.", "Everyone gather 'round. Let's have a good time."},
    {"$animal_ghoul", "Everyone here is cooler than me...", "I could corrode this whole place if I tried.", "See the world through glowing yellow eyes."},
    {"$animal_icemage", "Do you wanna build a snowman?", "The winter season never lasts long enough...", "Anyone want a drink? Iced."},
    {"$animal_statue", "Stare all you want. What else would I be here for?", "Why do so many consider life to be a gift?", "Break the curse, someone... please."},
    {"$animal_assassin", "Fortunately, there's no need to sharpen an energy weapon.", "I can make anyone disappear; just give me a call.", "I'm not a \"crazed\" assassin. Rather sensible, in fact."},
    {"$animal_drone_lasership", "Battery power low. Please recharge soon.", "Gravity is challenging for a heavy steel robot.", "If only they had implemented infrared sensors in my design."},
    {"$animal_miner_santa", "This place is... certainly no winter wonderland.", "I shall spread the cheer! Forcefully.", "Haaaappy holidays! I think."},
    {"$animal_cook", "Don't-a worry, I made enough to share!", "A tasty-a meal for everyone around!", "Here you go! Don't forget-a to share!"},
    {"$animal_lukki_tiny", "The Hiisi are so mean. Keep them out of our home...", "Thank you, guardians, for keeping us safe.", "So much to explore..."},
    {"$animal_lukki", "I'm still learning, I promise...", "It's interesting to just watch things change from a distance.", "Fire is the enemy. Fire is the end of all things..."},
    {"$animal_lukki_longleg", "It's so immature to destroy the world around you.", "Cherish what we have, friends, while it lasts.", "Once you start learning from nature, you never really stop."},
    {"$animal_bloom", "Pollination was just a second thought once sentience struck.", "Nothing here follows nature's rules. Isn't that odd?", "Knowledge, yes, but... Where is there to go?"},
    {"$animal_shooterflower", "I won't summon a plant boss when I die. Sadly.", "The scenery here is quite nice... but what about elsewhere?", "The grass is always greener in a different biome."},
    {"$graham_lukkimount_name", "Thanks again for saving me back then. I won't forget it.", "Feels like I was made for this. Hehe...", "My depth perception isn't great. I'm glad to have a pilot.", "Heh... where would I be without you?", "What's it like to have eyelids? Us spiders don't.", "I'm no good at pest removal, but I hope I can still help.", "This is great exercise for my legs. I'm glad that I can do it.", "No saddle for me. I'm a steed all on my own.", "Don't worry if I bump into a wall. It's kind of fun."},
    {"$animal_spearbot", "Everything looks so much smaller from a higher perspective.", "Looks can be deceiving. And robots aren't fragile.", "These arms have won quite a few lance-throwing competitions."},
    {"$animal_boss_dragon", "Don't bother hiding... I can smell you.", "According to all known laws of aviation, I shouldn't be able to fly.", "You know, it's rude to enter our tunnels while they're still occupied.", "It has been quite a while since my last haircut...", "I may be as red as a salmon, but nothing's fishy about me.", "It's a good thing that the jungle is so warm. I hate the cold..."},
    {"$animal_missilecrab", "No, I will not vacuum your floors. Stop asking.", "Due to budget cuts, I do not have the ability to fly or hover.", "Fossil fuels? The environment will not suffer... hopefully."},
    {"$animal_healerdrone_physics", "Bolts that can heal both natural and robotic creatures... How interesting.", "Pheromone is quite amusing. I would not fall for something like that.", "I wonder what the purpose was behind my sentience. Is there one?"},
    {"$animal_lasershooter", "What? Eyes? I don't know anything about any glyphs.", "Anyone got some eye drops? Please...", "Sweat and tears aren't that different, really."},
    {"$animal_worm_skull", "Sometimes I do just get the urge to destroy things, though...", "Ghosts are like sponges for magic. Nothing else can persist...", "Walls are a suggestion. Or a blueprint."},
    {"$animal_ghost", "No matter how many eyes I have, I'm blind...", "Maybe my next life will yield different results.", "Nothing feels real..."},
    {"$animal_failed_alchemist", "My mistake was abusing my art and those I held dear.", "I know... I know that this isn't what I wanted...", "Where is everyone? Oh..."},
    {"$animal_failed_alchemist_b", "My mistake was thinking that I was anything at all.", "I keep waking up, but this is just another nightmare...", "Look at me. Look at me."},
    {"$animal_enlightened_alchemist", "My mistake was leaving my old morals behind.", "It feels like my mind is swollen with slime...", "What's left of me? Why don't I know?"},
    {"$animal_wraith", "I'm an expert at conflict resolution. Right?", "We don't have vacuum cleaners around here, unfortunately.", "Not all who wander are lost. Hopefully."},
    {"$animal_wraith_glowing", "Light and dark aren't always good and evil.", "Mirror, mirror, on the wall...", "Don't stare too hard. You'll give yourself sunburn."},
    {"$animal_wraith_storm", "Stormy skies await you all.", "One day, the clouds will close in.", "Don't fly too close to the sun."},
    {"$animal_skullrat", "There's lots of room for scrounging, here in this tomb.", "Some day I'll find a big enough skull, and then...", "If you steal something for long enough, then you own it, right?"},
    {"$animal_skullfly", "This brickwork is older than all of us. Best show some respect.", "We're more than just the sum of our parts.", "Sometimes it's just easier to appreciate someone in death."},
    {"$animal_crystal_physics", "Crystals are such pretty husks to occupy...", "Perhaps I should've chosen a more discreet form.", "It's a lot of fun to be a bit haphazard sometimes."},
    {"$animal_lurker", "The poison runs as deep as the darkness down here.", "This place just drains the light from every poor soul...", "It's pure darkness inside and out."},
    {"$animal_lukki_creepy_long", "A good sense of touch can light darkness like nothing else.", "The spiders in the jungle think that I'm odd. That's alright.", "Someone has to keep the folks here company, right?"},
    {"$animal_lukki_dark", "Gnaaaah!", "Nothing shall escape!", "I'll shred this whole place to bits!"},
    {"$animal_worm_end", "As above, so below... But my reflection is lost.", "What's lost may never be found, down here.", "Rumors say that not a single soul has escaped my jaws alive."},
    {"$animal_gazer", "Don't cry when the show's over.", "A hellish punishment awaits you.", "Don't look up."},
    {"$animal_skygazer", "Tears in the eye...", "A divine punishment awaits you.", "Don't look down."},
    {"$animal_friend", "It's my job to protect my children, no matter what.", "I'm glad to provide a safe haven for everyone.", "It takes a lot of effort to go off the record around here.", "I think I misspelled \"friendship\"... I'm still practicing my glyphs.", "What? \"Baba\"? I don't know anyone named that.", "Nature is truly beautiful."},
    {"$animal_ultimate_killer", "Hooray!", "Friends!", "Plants are nice!"},
    {"$animal_thundermage_big", "Very few can survive a single blast of my power.", "Why's it so damn cold out here?!", "I've been itching to take my anger out on something..."},
    {"$animal_bloodcrystal_physics", "Crystals reflect the light of the lava so nicely.", "Maybe I should just ditch this body and move north.", "Maybe a purple crystal would be nice to inhabit."},
    {"$animal_skycrystal_physics", "Crystals reflect the sunlight so beautifully.", "I'm sometimes tempted to leave this body and move south.", "Perhaps green would be a nice look on me instead."},
    {"$animal_spitmonster", "Blargh! This place stinks!", "Please bring me a toothbrush.", "Perhaps... It's best to lose your reflection sometimes."},
    {"$animal_necrobot", "I haven't oiled the treads recently, hmm...", "What tedium, resurrecting these fragile mortals.", "Is no one here satisfied with their purpose? How sad."},
    {"$animal_necrobot_super", "Jeez, where can a robot get some lens wipes around here?", "I'm so tired of steel. Nothing but steel, everywhere...", "For most people, turning into a little slimy thing is somehow an upgrade."},
    {"$animal_minipit", "Life energy can be very powerful when simply reformed.", "And it never ends and it never ends...", "Sorry, no staring contest today."},
    {"$animal_piranha", "Each new revision brings new optimizations.", "There's never enough code to cover every edge case...", "At least I can solve most of my problems with this gun."},
    {"$animal_shotgunner_hell", "The heart and soul went missing a long time ago.", "This marks the beginning of a new age...", "Stay in this realm long enough, you might become one of us."},
    {"$animal_sniper_hell", "Bullets kill. That's one of the constants of this world.", "You don't want to know what I look like beneath this mask.", "I have to restrain myself... Shouldn't use every bullet at once."},
    {"$animal_miner_hell", "Nothing else matters if everyone around you is dead.", "I'll blow this whole place skyward soon enough.", "Let's see how big of a crater I can create before I die."},
    {"$animal_graham_gasser_hell", "I only wear this hazmat suit to keep myself held together...", "Stay away if you don't want your skin dissolved. Seriously.", "I can singlehandedly lower the air quality by over " .. tostring(Random(234, 567)) .. "%."},
    {"$animal_drone_shield", "It is much easier to think when we are all in stalemate.", "Do not ask how my work is done. The end result is what matters.", "Fireproofing everything here was a worthwile investment..."},
    {"$animal_hidden", "I begin the hunt. Others will end it.", "Some people do not listen carefully. What a mistake.", "Flight helps greatly to stay unstained and pristine..."},
    {"$animal_soldier", "You all chip the enemy down. I will finish the job.", "Blood is a good indicator that I am doing my job well.", "Guillotines are quite flamboyant. Perhaps impractical."},
    {"$animal_neutralizer", "No good fights happen alone. Let me assist.", "Sometimes technology can indeed prevail over magic.", "We have not figured out how to slow down enemy flight yet..."},
    {"$animal_sentry", "Who shall we attack? Let me decide.", "A good plan helps keep things moving in the right direction.", "The Class-D Guardians? They're friends of mine, yes..."},
    {"$animal_ethereal_being", "Everything was so much different back then...", "Three eyes bring wisdom. Nothing good comes from two.", "Feels like knowledge so easily flies away from me..."},
    {"$animal_fish_giga", "Land-dweller, face the truth. You don't belong here.", "The pressure down here would crush any lesser beings.", "I'll teach you the true meaning of thalassophobia.", "What could even drive someone to venture down here, I wonder...", "I can smell blood in the water.", "You're not the only one with powerful hidden magic."},
    {"$animal_boss_limbs", "Death is a part of nature. The two cannot be separated.", "A new old life awaits those who fall down.", "Rebirth comes in all shapes and sizes.", "Some walk, some fly, some climb. All die.", "The most unusual thing in this world is something dying forever.", "It all moves in cycles. Each end is a new beginning."},
    {"$animal_slimeshooter_boss_limbs", "Eternally thankful for eternal life.", "I must prove my devotion. It's worth it.", "Whatever it takes. I will demonstrate..."},
    {"$animal_chest_leggy", "No more disguises. I'm being my true self!", "I would kill for some shoes right about now.", "All those other mimics just WISH they were me."},
    {"$animal_fungus_tiny", "What's my name...?", "Forgotten, but not gone.", "Only one thing left to do."},
    {"$animal_fungus_tiny_perk", "Let's do this.", "Bring the slime! Spread this...", "Life is short. Eat fungus."},
    {"$animal_mini_mimic", "...", "...?", "...!"},
    {"$animal_bloody_mimic", "...", "...?", "...!"},
    {"$animal_homunculus", "Spitting out my projectiles isn't elegant, but it works...", "Sorry. There's not much brain in my head.", "Call me up if you need any more firepower."},
}

---@type string[]
GENERIC_HOLDINGWAND =
    { "How do you work this thing?", "Guys, look at this thing I found! Isn't this cool?", "Hey, does anyone here own this? No? Finders keepers.", "If I write my name on this, that means it's mine, right?", "I have no idea what this does, but I'm not afraid to use it!", "Oh boy, I hope this one is a nuke!", "Hey, how do I put bullets into this?",
}

---@type string[]
GENERIC_CHARMED =
    { "I'm just happy to be here.", "Hello! How are you? I love you.", "Friendship...", "You're my best friend.", "Hehe...",
}

---@type string[]
GENERIC_ONFIRE =
    { "Ow, ow!", "Aaah!", "Water! Need water, quickly!", "Someone help!", "Fire! Fire!!", "It burns! Help!",
}

---@type string[]
GENERIC_PEACEFULENDING =
    { "This is nice.", "Thank you, player!", "So peaceful... so nice!", "I feel so happy!", "I can finally take a nap...",
}

---@type string[]
GENERIC_DRUNK =
    { "Hic...", "Y-you're funny.", "Burp.", "My head hurts...", "Oof, I've had too much.",
}

---@type string[]
GENERIC_BERSERK =
    { "I'll kill you all!", "Prepare to die!", "I'll tear you all to pieces!", "None of you are my allies!", "Surrender now! Die! Die!",
}

---@type string[]
GENERIC_TOXIC =
    { "Oh, I feel gross...", "Cough, hack...", "My head hurts...", "I feel like I'm gonna be sick...", "It hurts...",
}

---@type string[]
GENERIC_HEALED =
    { "Ahh, that feels better.", "That's a weight off my back.", "I feel as good as new!", "Thanks for that.", "Perhaps I'll live another day.",
}

---@type string[]
GENERIC_FRIENDLYFIRE =
    { "Hey! Who did that?!", "Don't attack me!", "Stay away!", "Why can't we just be allies?!", "Hey, who do you think you are?!", "You'll pay for that!", "We're supposed to fight them, not each other!",
}

---@type string[][]
Custom_speak_lines = {
    {"angry_ghost", "Who would dare fight us with this much firepower?!", "Together, we can take on anyone!", "Just use an empty wand, even! I can do the rest.", "Hey, the best battles never happen alone!", "Keep me away from explosives. I get too excited.", "Teach me more spells! Let me destroy more!"},
    {"hungry_ghost", "Projectiles are a delicacy. Hard to catch them.", "I eat the bullets so that you don't have to.", "You think eating bullets is strange? How do I eat at all?", "Try not to heal yourself while I'm making your spells stronger.", "The Magic Guard spells taste incredible, for the record.", "I'm not fat! I just absorbed too many projectiles earlier..."},
    {"mournful_spirit", "How far can we spread this plague of death?", "This can't be taken back, you know...", "I've learned so much since this began.", "Lure your foes to me. I'll make sure they regret it.", "It's too late for tears. I only have one purpose now.", "Sorry if I bring the mood down. It's part of the job."},
    {"tipsy_ghost", "Hurp... You can c-count on me, boss...", "G-glad to be here.", "Got any spare whiskey or sima? I'll m-make it worth your while.", "I can do lots of stuff! If my head is clear...", "I'm a spirit spirit! Get it...?", "Stay away from my whiskey! ...For your health, I mean."},
    {"tiny_ghost", "This is quite the ghostly reunion, isn't it?", "Hello, ghost folks! Have we met before?", "Life is short... But being a ghost lasts forever!", "I'm not nearly as strong as your angry friend over there.", "I would love to be friends with that hungry ghost, but I'm so shy...", "I always try to keep my 'spirits' up, hehe."},
    {"ghostly_ghost", "My little brother asked me to come along. You seem nice...", "I've never seen so many ghosts in one place before...", "You might become a ghost one day. Wouldn't that be neat?", "What? I'm just here to keep you company. I don't fight.", "Us ghosts make you floatier, don't you know?", "Come on, guys, we go as ghosts every Halloween..."},
    {"karl", "Modifying the course is against the rules, by the way.", "I typically stay in my course, but it's fun to explore too!", "Bumping walls to turn can be both fun and effective!", "This cart isn't ever gonna run out of power.", "I haven't seen much... Wanna go somewhere?", "I'm so popular, even the stars are attracted to me."},
    {"karl_lap", "New best time! I knew you could do it!", "That lap was great! Wanna do another?", "I'm proud to have you as my driver.", "Woah! I didn't know that you could do it that fast!", "We should try going in the opposite direction next time!", "Yes! That one was super quick!"},
    {"boss_limbs_death", "Wait, this isn't right! I'm not ready!", "What did you do? Why can't I hold myself together anymore?!", "I'm sorry for what I said! I didn't mean it, I swear!", "T-the offer's still on the table to join me, right...?", "It hurts... How does it hurt?! This is insane!", "Oh... You've really done it now, haven't you..."},
    {"minitank", "AAA batteries do not last that long, unfortunately.", "Pew pew pew.", "A little bit of magic can go a long way.", "Circuit boards and computer chips... Everything that is 'me'.", "More sleek and lightweight than any common tank out there.", "I am not a wind-up toy. What a shame."},
    {"Calamariface", "Time's up. If you can't outrun me, you're dead.", "What makes you think that you can outrun death?", "Let's see if I can't teach you a thing or two...", "You've wasted far too much time on a simple jog to the final floor!", "No P-rank awaits you at the end of this run.", "The stakes are high. You're not gonna win this race."},
    {"lukki_minion", "Glad I could tag along! I'll feed on your enemies...", "Bullets are funny. My skin is too tough for them to hurt...", "I'm no facehugger, but I hate to let go of foes...", "Come here, friends! Let me take a bite out of you!", "Hmm... I'm still hungry, though...", "I'd hate to wander off... Ooh, but what's that over there?"},
    {"swarm_fly", "Frozen foes are a joy to nibble on.", "At least flies don't have as bad of a reputation as wasps do...", "Don't worry, I'm no fruit fly.", "No one remembers the flies, until they come back to bite ya.", "'Flies are gross'? I think you're gross.", "So many fresh bodies to feast upon..."},
    {"swarm_firebug", "Death can spread like a wildfire.", "It's fun to watch people panic when they're set ablaze.", "Don't stop, drop, or roll. I hate when people do that."},
    {"swarm_wasp", "Buzz, buzz, and all that.", "What common housefly could stand up to the mighty wasp?", "Sting, sting, sting. What a simple joy."},
}